### PR TITLE
Add a new type for adding/removing channels

### PR DESCRIPTION
**Pull request by alexjfisher**
Hi

I've added a new rhn_channel type/provider.  Username and password are mandatory.

rhn_channel { 'channel-name':
  username => 'user',
  password => 'password',
}

There's a unit test for the type.  I've also added a new fact which I found useful in my manifests.

Feedback and suggested improvements very welcome,
Alex

### CODE REVIEW

**Comment by strider** [comment]
Hi Alex,
Can I bother you to add some information into the README.md file about the new type?
By the way, it looks good to me!

**Comment by strider** [comment]
Can you remove the extra spaces in spec/unit/puppet/type/rhn_channel_spec.rb, please?
And rebase your commits with https://github.com/strider/puppet-rhnreg_ks/commit/f9e3ddc0fa304d0a634412d4bd5812849fda35a5?

**Comment by alexjfisher** [comment]
Rebased (and some commits squashed too).  Travis build is failing with some combinations.  Any ideas?

**Comment by strider** [comment]
Yes it failed with puppet 2.7 and it should be ignored!
WIll remove the puppet 2.7 tests...

Thanks for this new type/provider!

**Comment by strider** [comment]
Looks good to me, but will merge it once the README.md will be updated! ;-)

**Comment by alexjfisher** [comment]
README.md updated. :)

**Pull request merged**
